STORAGE_DIR = "/run/media/keith/a1cdd4e6-1c93-4b0a-8e04-b49b3dfb68d9"
STORAGE_DIR_DATA_FLEURS = STORAGE_DIR + "/data/fleurs"
STORAGE_DIR_DATA_FLORES_PLUS = STORAGE_DIR + "/data/flores_plus"
STORAGE_DIR_MODEL_WHISPER = STORAGE_DIR + "/models/whisper"
STORAGE_DIR_MODEL_MMS_1B_ALL = STORAGE_DIR + "/models/mms-1b-all"
STORAGE_DIR_MODEL_MBART_LARGE_50_MANY_TO_ONE = STORAGE_DIR + "/models/mbart-large-50-many-to-one-mmt"
STORAGE_DIR_MODEL_MBART_LARGE_50_MANY_TO_MANY = STORAGE_DIR + "/models/mbart-large-50-many-to-many-mmt"